### ISSUE TITLE
Impossible to launch optimize_images.py

### ISSUE THREAD

**Issue by JoffreyLGT** [JoffreyLGT/e-commerce-mlops#138]
When running optimize_images.py, an error occurs because ROOT_DIR is not in settings anymore.

**Comment by JoffreyLGT** [comment]
Here is the error : 

```shell
❯ python -m scripts.optimize_images --train-size 0.01 --test-size 0.01 --input-dir "data/originals" --output-dir "data/datasets/test"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/joffrey/workspace/e-commerce-mlops.worktrees/optimize-images/datascience/scripts/optimize_images.py", line 472, in <module>
    args = parser.parse_typed_args()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joffrey/workspace/e-commerce-mlops.worktrees/optimize-images/datascience/.venv/lib/python3.11/site-packages/pydantic_argparse/argparse/parser.py", line 160, in parse_typed_args
    model = self.model.parse_obj(arguments)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 898, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 304, in pydantic.class_validators._generic_validator_cls.lambda4
  File "/Users/joffrey/workspace/e-commerce-mlops.worktrees/optimize-images/datascience/scripts/optimize_images.py", line 404, in must_contain_data
    path=path, root_dir=Path(get_common_settings().ROOT_DIR)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_CommonSettings' object has no attribute 'ROOT_DIR'. Did you mean: 'LOGS_DIR'?
```

Working on the fix.
